sudo: true
dist: trusty
language: c

# safelist
branches:
  only:
  - master
    
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath
  
install:
  - ./.ci/prepare-epics.sh

script:
  - ./.ci/build-epics.sh
