sudo: true
dist: trusty
language: c

# safelist
branches:
  only:
  - target_path_test
    
before_install:
  - sudo apt-get -qq update
  
install:
  - ./.ci/prepare-epics.sh

script:
  - ./.ci/build-epics.sh